name: Generate Snake

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows you to run it manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
          uses: Platane/snk@v3
          with:
            github_user_name: Indipa9
            outputs: |
              dist/snake.svg
              dist/snake-dark.svg?palette=github-dark

      - name: Push snake animation to repo
          uses: EndBug/add-and-commit@v9
          with:
            message: "Generated snake animation"
            add: "dist/snake.svg dist/snake-dark.svg"
